### ISSUE TITLE
Storybook code examples have bad formatting

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#537] opened 2021-10-14 23:45 UTC
![image](https://user-images.githubusercontent.com/3260989/137410128-b9b0665a-f2fa-40b8-a703-e77c840b4b9b.png)

**Comment by kvisca** [comment] 2021-11-26 20:23
@ScopeyNZ is this referring to the color or the spacing?

**Comment by ScopeyNZ** [comment] 2021-11-26 20:37
The colour. Is the spacing bad?

**Comment by kvisca** [comment] 2021-11-26 21:21
Nope, just wanted to check. #563 was a duplicate of this issue so it can be closed.

**Closed by kvisca** 2021-11-26 21:21 UTC
Labels: bug

**Comment by ScopeyNZ** [comment] 2021-11-26 22:08
Eh? That seems like a completely different issue
